version: '3'

volumes:
  database_data:
    driver: local

services:
  db:
    build: ./db
    ports:
        - 5432:5432
    volumes:
      - database_data:/var/lib/postgresql/data

  api:
    build: .
    ports:
      - 8000:8000
    volumes:
      - ./api:/usr/src/app/
    links:
      - db
    environment:
      - PG_HOST=db
      - PG_DATABASE=postgres_test_db
      - PG_USER=postgres_test_user
      - PG_PASSWORD=any_password_you_know
      - PG_PORT=5432
    command: "python manage.py runserver --host=0.0.0.0 --port=8000"
    depends_on:
        - db
