"""empty message

Revision ID: 2504bde8f23f
Revises: 614688772f08
Create Date: 2019-12-09 15:36:43.869599

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2504bde8f23f'
down_revision = '614688772f08'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('books_owner_id_fkey', 'books', type_='foreignkey')
    op.drop_column('books', 'owner_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('books_owner_id_fkey', 'books', 'users', ['owner_id'], ['id'])
    # ### end Alembic commands ###
