"""empty message

Revision ID: 2f6390b93567
Revises: 2504bde8f23f
Create Date: 2019-12-09 16:12:39.371612

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f6390b93567'
down_revision = '2504bde8f23f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('user_id', sa.Integer(), nullable=True))
    op.drop_constraint('books_current_user_id_fkey', 'books', type_='foreignkey')
    op.create_foreign_key(None, 'books', 'users', ['user_id'], ['id'])
    op.drop_column('books', 'current_user_id')
    op.add_column('library', sa.Column('book_id', sa.Integer(), nullable=True))
    op.add_column('library', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.drop_constraint('library_book_fkey', 'library', type_='foreignkey')
    op.drop_constraint('library_owner_fkey', 'library', type_='foreignkey')
    op.create_foreign_key(None, 'library', 'users', ['owner_id'], ['id'])
    op.create_foreign_key(None, 'library', 'books', ['book_id'], ['id'])
    op.drop_column('library', 'book')
    op.drop_column('library', 'owner')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('library', sa.Column('owner', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('library', sa.Column('book', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'library', type_='foreignkey')
    op.drop_constraint(None, 'library', type_='foreignkey')
    op.create_foreign_key('library_owner_fkey', 'library', 'users', ['owner'], ['id'])
    op.create_foreign_key('library_book_fkey', 'library', 'books', ['book'], ['id'])
    op.drop_column('library', 'owner_id')
    op.drop_column('library', 'book_id')
    op.add_column('books', sa.Column('current_user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'books', type_='foreignkey')
    op.create_foreign_key('books_current_user_id_fkey', 'books', 'users', ['current_user_id'], ['id'])
    op.drop_column('books', 'user_id')
    # ### end Alembic commands ###
