"""empty message

Revision ID: 34d987a5b4f7
Revises: 41599dd7a896
Create Date: 2019-12-09 18:13:35.690457

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34d987a5b4f7'
down_revision = '41599dd7a896'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('books_current_owner_fkey', 'books', type_='foreignkey')
    op.drop_column('books', 'current_owner')
    op.add_column('library', sa.Column('book_id', sa.Integer(), nullable=True))
    op.add_column('library', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.drop_constraint('library_book_fkey', 'library', type_='foreignkey')
    op.drop_constraint('library_owner_fkey', 'library', type_='foreignkey')
    op.create_foreign_key(None, 'library', 'books', ['book_id'], ['id'])
    op.create_foreign_key(None, 'library', 'users', ['owner_id'], ['id'])
    op.drop_column('library', 'owner')
    op.drop_column('library', 'book')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('library', sa.Column('book', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('library', sa.Column('owner', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'library', type_='foreignkey')
    op.drop_constraint(None, 'library', type_='foreignkey')
    op.create_foreign_key('library_owner_fkey', 'library', 'users', ['owner'], ['id'])
    op.create_foreign_key('library_book_fkey', 'library', 'books', ['book'], ['id'])
    op.drop_column('library', 'owner_id')
    op.drop_column('library', 'book_id')
    op.add_column('books', sa.Column('current_owner', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('books_current_owner_fkey', 'books', 'users', ['current_owner'], ['id'])
    # ### end Alembic commands ###
