"""empty message

Revision ID: 41599dd7a896
Revises: 7b0b92eef86b
Create Date: 2019-12-09 17:05:28.595534

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41599dd7a896'
down_revision = '7b0b92eef86b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('current_owner', sa.Integer(), nullable=True))
    op.drop_constraint('books_owner_fkey', 'books', type_='foreignkey')
    op.create_foreign_key(None, 'books', 'users', ['current_owner'], ['id'])
    op.drop_column('books', 'owner')
    op.add_column('library', sa.Column('book', sa.Integer(), nullable=True))
    op.add_column('library', sa.Column('owner', sa.Integer(), nullable=True))
    op.drop_constraint('library_owner_id_fkey', 'library', type_='foreignkey')
    op.drop_constraint('library_book_id_fkey', 'library', type_='foreignkey')
    op.create_foreign_key(None, 'library', 'users', ['owner'], ['id'])
    op.create_foreign_key(None, 'library', 'books', ['book'], ['id'])
    op.drop_column('library', 'owner_id')
    op.drop_column('library', 'book_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('library', sa.Column('book_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('library', sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'library', type_='foreignkey')
    op.drop_constraint(None, 'library', type_='foreignkey')
    op.create_foreign_key('library_book_id_fkey', 'library', 'books', ['book_id'], ['id'])
    op.create_foreign_key('library_owner_id_fkey', 'library', 'users', ['owner_id'], ['id'])
    op.drop_column('library', 'owner')
    op.drop_column('library', 'book')
    op.add_column('books', sa.Column('owner', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'books', type_='foreignkey')
    op.create_foreign_key('books_owner_fkey', 'books', 'users', ['owner'], ['id'])
    op.drop_column('books', 'current_owner')
    # ### end Alembic commands ###
