"""empty message

Revision ID: 46fd371fa9eb
Revises: 
Create Date: 2019-12-09 12:43:00.930128

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46fd371fa9eb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('current_user', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'books', 'users', ['current_user'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'books', type_='foreignkey')
    op.drop_column('books', 'current_user')
    # ### end Alembic commands ###
