"""empty message

Revision ID: 54b6e3ea3f72
Revises: 
Create Date: 2019-11-26 00:49:37.034136

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54b6e3ea3f72'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('book')
    op.drop_table('user')
    op.drop_constraint('library_user_id_fkey', 'library', type_='foreignkey')
    op.drop_constraint('library_book_id_fkey', 'library', type_='foreignkey')
    op.create_foreign_key(None, 'library', 'books', ['book_id'], ['id'])
    op.create_foreign_key(None, 'library', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'library', type_='foreignkey')
    op.drop_constraint(None, 'library', type_='foreignkey')
    op.create_foreign_key('library_book_id_fkey', 'library', 'book', ['book_id'], ['id'])
    op.create_foreign_key('library_user_id_fkey', 'library', 'user', ['user_id'], ['id'])
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='user_pkey')
    )
    op.create_table('book',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('author', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('edition', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('year_of_publication', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('translator', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='book_pkey')
    )
    # ### end Alembic commands ###
