"""empty message

Revision ID: 614688772f08
Revises: 12c67caedc72
Create Date: 2019-12-09 15:30:56.604866

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '614688772f08'
down_revision = '12c67caedc72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'books', 'users', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'books', type_='foreignkey')
    op.drop_column('books', 'owner_id')
    # ### end Alembic commands ###
