"""empty message

Revision ID: 7b0b92eef86b
Revises: 2f6390b93567
Create Date: 2019-12-09 16:45:41.677623

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b0b92eef86b'
down_revision = '2f6390b93567'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('owner', sa.Integer(), nullable=False))
    op.drop_constraint('books_user_id_fkey', 'books', type_='foreignkey')
    op.create_foreign_key(None, 'books', 'users', ['owner'], ['id'])
    op.drop_column('books', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'books', type_='foreignkey')
    op.create_foreign_key('books_user_id_fkey', 'books', 'users', ['user_id'], ['id'])
    op.drop_column('books', 'owner')
    # ### end Alembic commands ###
