"""empty message

Revision ID: f48a48c4d693
Revises: 46fd371fa9eb
Create Date: 2019-12-09 12:59:21.130243

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f48a48c4d693'
down_revision = '46fd371fa9eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('current_user_id', sa.Integer(), nullable=True))
    op.drop_constraint('books_current_user_fkey', 'books', type_='foreignkey')
    op.create_foreign_key(None, 'books', 'users', ['current_user_id'], ['id'])
    op.drop_column('books', 'current_user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('current_user', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'books', type_='foreignkey')
    op.create_foreign_key('books_current_user_fkey', 'books', 'users', ['current_user'], ['id'])
    op.drop_column('books', 'current_user_id')
    # ### end Alembic commands ###
